name: appeler
description: A new Flutter project.
publish_to: 'none'
version: 1.1.0+11

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  app_color: ^0.0.2
  cupertino_icons: ^1.0.2
  firebase_core: ^2.12.0
  firebase_core_platform_interface: ^4.8.0
  shared_preferences: ^2.1.1
  flutter_webrtc:
    git:
      url: https://github.com/flutter-webrtc/flutter-webrtc.git
      ref: main
  wakelock: ^0.6.2
  flutter_bloc: ^8.1.2
  equatable: ^2.0.5
  upgrader: ^6.3.0
  flutter_svg: ^2.0.5
  get_it: ^7.3.0
  camera: ^0.10.5
  share_plus: ^6.3.4
  flutter_foreground_task: ^5.2.1
  focused_menu: ^1.0.5
  device_info_plus: ^8.2.2
  go_router: ^9.0.1
  carousel_slider: ^4.2.1
  fluttertoast: ^8.2.2
  url_strategy: ^0.2.0
  package_info_plus: ^3.1.2
  uni_links: ^0.5.1
  auth_management: ^0.1.0
  data_management: ^0.0.9-alpha2
  flutter_andomie: ^0.4.9
  flutter_androssy: ^0.2.8-alpha2
  firebase_auth: ^4.10.0
  socket_io_client: ^2.0.3+1
  connectivity_plus: ^4.0.2
  dio: ^5.3.3
  ed_screen_recorder: ^0.0.13
  whiteboard: ^0.0.2

#flutter_tools:
#  web-server:
#    port: 8080

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
    android: "ic_launcher_icon"
    ios: true
    remove_alpha_ios: true
    image_path: "assets/icons/ic_launcher_new.png"
    web:
      generate: true
      image_path: "assets/icons/ic_launcher_new.png"

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
#  custom_server:
#    port: 8080