name: appeler
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  app_color: ^0.0.2
  flutter_andomie: ^0.3.0
  cupertino_icons: ^1.0.2
  cloud_firestore: ^4.7.0
  firebase_core: ^2.12.0
  firebase_core_platform_interface: ^4.8.0
  shared_preferences: ^2.1.1
  flutter_webrtc:
    git:
      url: https://github.com/flutter-webrtc/flutter-webrtc.git
      ref: main
  wakelock: ^0.6.2
  encrypt: ^5.0.1
  dio: ^5.1.1
  firebase_messaging: ^14.4.1
  flutter_bloc: ^8.1.2
  equatable: ^2.0.5
  upgrader: ^6.3.0
  flutter_svg: ^2.0.5
  get_it: ^7.3.0
  camera: ^0.10.5
  share_plus: ^6.3.4
  local_auth: ^2.1.6
  flutter_facebook_auth: ^5.0.11
  firebase_database: ^10.2.1
  firebase_auth: ^4.6.1
  flutter_foreground_task: ^5.2.0

#flutter_tools:
#  web-server:
#    port: 8080

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
#  custom_server:
#    port: 8080